apiVersion: v1
kind: Namespace
metadata:
  name: adi-test

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicea
  namespace: adi-test
spec:
  selector:
    matchLabels:
      app: servicea
  replicas: 1
  template:
    metadata:
      labels:
        app: servicea
    spec:
      containers:
      - name: servicea
        image: ${DOCKER_IMAGE_NAME}:${BUILD_NUMBER}
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        startupProbe:
          httpGet:
            path: /health
            port: 5001
          failureThreshold: 6
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 1
          periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: servicea-service
  namespace: adi-test
spec:
  ports:
  - nodePort: 31154
    port: 5002
    protocol: TCP
    targetPort: 5001
  selector:
    app: servicea
  sessionAffinity: None
  type: LoadBalancer
