kind: ConfigMap 
apiVersion: v1 
metadata:
  name: getrequest-cm
data:
  # Configuration values can be set as key-value properties
  GET_REQUEST: http://random-numbers-service.adi-test.svc.cluster.local:5001/api/serviceA
