apiVersion: v1
kind: Namespace
metadata:
  name: adi-test

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: getrequest-cm
data:
  # Configuration values can be set as key-value properties
  GET_REQUEST: http://servicea-service.adi-test.svc.cluster.local:5002/api/serviceA

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceb
  namespace: adi-test
spec:
  selector:
    matchLabels:
      app: serviceb
  replicas: 1
  template:
    metadata:
      labels:
        app: serviceb
    spec:
      containers:
      - name: serviceb
        image: mandeep1690/serviceb:0.0.2
        imagePullPolicy: Always
        envFrom:
          -  configMapRef:
               name: getrequest-cm
        ports:
        - containerPort: 8080
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 6
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: serviceb-service
  namespace: adi-test
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8080
  selector:
    app: serviceb
  sessionAffinity: None
  type: LoadBalancer

---
