apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceB
  namespace: adi-test
spec:
  selector:
    matchLabels:
      app: serviceB
  replicas: 1
  template:
    metadata:
      labels:
        app: serviceB
    spec:
      containers:
      - name: serviceB
        image: mandeep1690/serviceb:0.0.1
        imagePullPolicy: Always
