apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appservicea.fullname" . }}
spec:
  selector:
    matchLabels:
      app: servicea
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: servicea
    spec:
      serviceAccountName: {{ include "appservicea.serviceAccountName" . }}
      containers:
      - name: servicea
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8081
        startupProbe:
          httpGet:
            path: /health
            port: 8081
          failureThreshold: 6
          periodSeconds: 10
        livenessProbe:
         httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 1
          periodSeconds: 3
